from .modelo import Modelo, ModeloSupervisado
from .modelo_kmeans import ModeloKMeans
from .modelo_regresion_lineal import ModeloRegresionLineal
from .modelo_regresion_logistica import ModeloRegresionLogistica
from .modelo_arbol_decision import ModeloArbolDecision
from .modelo_knn import ModeloKNN
from .modelo_random_forest import ModeloRandomForest
from .modelo_knn_regresion import ModeloKNNRegresion
from .modelo_arbol_regresion import ModeloArbolRegresion
from .modelo_random_forest_regresion import ModeloRandomForestRegresion
from .modelo_naive_bayes import ModeloNaiveBayes
from .modelo_red_neuronal import ModeloRedNeuronal
from .modelo_red_neuronal_regresion import ModeloRedNeuronalRegresion
